// Platform abstraction for the Jade VM.
//
// This crate defines:
//   - `State` trait  – slot read/write, flushing, parent-state snapshot
//   - `Ops` trait    – value constructors and opcode handlers (return values)
//   - `exec_op`      – generated dispatch from `Operation` → State + Ops methods
//   - `resolve`      – convert an `Operand` to a platform value
//
// `dispatch.rs` is generated by `scripts/regen.ts`.

pub mod dispatch;
pub use dispatch::{Ops, State, exec_op, resolve};
