// Platform abstraction for the Jade VM.
//
// This crate defines:
//   - `Platform` trait  – implemented by each target (e.g. jade-vm-wasm)
//   - `exec_op`         – generated dispatch from `Operation` → Platform methods
//   - `resolve`         – convert an `Operand` to a platform value
//
// `dispatch.rs` is generated by `scripts/regen.ts`.

pub mod dispatch;
pub use dispatch::{Platform, exec_op};

use portal_solutions_jade_vm::Operand;

/// Convert an `Operand` to a platform value.
///
/// Literal operands produce a numeric JS value; state-ref operands read from
/// the platform's state (which may go through a cache on WASM).
pub fn resolve<P: Platform>(op: Operand, platform: &mut P) -> P::Value {
    match op {
        Operand::Literal(v) => platform.f64_val(v as f64),
        Operand::StateRef(idx) => platform.get(idx),
    }
}
