// Bytecode interpreter for the Jade VM – WASM / wasm-bindgen platform.
//
// Four public variants mirror the JS vm.ts exports:
//   run_virtualized      - sync
//   run_virtualized_a    - async (awaits JS Promises)
//   run_virtualized_g    - sync generator  (returns a JS iterator object)
//   run_virtualized_ag   - async generator (returns a JS async-iterator object)
//
// Bytecode decoding uses `Operation::parse` from `portal_solutions_jade_vm`.
// Opcode dispatch uses `jade_vm_core::exec_op` (generated by regen.ts).
// This crate supplies `WasmPlatform`: the `jade_vm_core::State + Ops` impl
// for the wasm-bindgen / JsValue target.

#![allow(unused_imports)]

extern crate alloc;

use alloc::{string::String, vec::Vec};
use core::cell::RefCell;

use js_sys::{Array, Function, Object, Promise, Reflect, Uint32Array, WeakMap};
use portal_solutions_jade_vm::{Operand, Operation, SignedOperand};
use portal_solutions_jade_vm_core as jade_vm_core;
use jade_vm_core::{State as _, Ops as _}; // bring trait methods into scope
use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::{JsFuture, future_to_promise};

// ---------------------------------------------------------------------------
// Raw JS bindings
// ---------------------------------------------------------------------------

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = Object, js_name = create)]
    fn js_object_create(proto: &JsValue) -> JsValue;

    #[wasm_bindgen(js_namespace = Object, js_name = assign)]
    fn js_object_assign(target: &JsValue, source: &JsValue) -> JsValue;

    #[wasm_bindgen(js_namespace = Object, js_name = defineProperties)]
    fn js_define_properties(target: &JsValue, props: &JsValue) -> JsValue;

    #[wasm_bindgen(js_namespace = Object, js_name = freeze)]
    fn js_object_freeze(obj: &JsValue) -> JsValue;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

#[inline]
fn js_err(s: &str) -> JsValue {
    JsValue::from_str(s)
}

#[inline]
fn s_get(state: &JsValue, idx: u32) -> JsValue {
    Reflect::get(state, &JsValue::from_f64(idx as f64)).unwrap_or(JsValue::UNDEFINED)
}

#[inline]
fn s_set(state: &JsValue, idx: u32, val: JsValue) {
    let _ = Reflect::set(state, &JsValue::from_f64(idx as f64), &val);
}

#[inline]
fn create_null_obj() -> JsValue {
    js_object_create(&JsValue::null())
}

fn make_iter_result(value: JsValue, done: bool) -> JsValue {
    let obj = create_null_obj();
    let _ = Reflect::set(&obj, &JsValue::from_str("value"), &value);
    let _ = Reflect::set(&obj, &JsValue::from_str("done"), &JsValue::from_bool(done));
    obj
}

/// Invoke an object-manager method (`make`/`get`/`set`/`define`/`assign`/…) on
/// the tenant, with `tenant` as the `this` receiver. Returns `undefined` if the
/// method is missing or throws.
fn tenant_call(tenant: &JsValue, method: &str, args: &[JsValue]) -> JsValue {
    match Reflect::get(tenant, &JsValue::from_str(method)) {
        Ok(f) if f.is_function() => {
            let a = Array::new();
            for arg in args {
                a.push(arg);
            }
            Reflect::apply(f.unchecked_ref::<Function>(), tenant, &a).unwrap_or(JsValue::UNDEFINED)
        }
        _ => JsValue::UNDEFINED,
    }
}

// ---------------------------------------------------------------------------
// StateCache – caches JS state object slots to reduce Reflect bridge crossings
// ---------------------------------------------------------------------------

struct StateCache {
    state: JsValue,
    slots: Vec<Option<JsValue>>,
    dirty: Vec<u32>,
}

impl StateCache {
    fn new(state: JsValue) -> Self {
        Self { state, slots: Vec::new(), dirty: Vec::new() }
    }

    fn get(&mut self, idx: u32) -> JsValue {
        let i = idx as usize;
        if i < self.slots.len() {
            if let Some(v) = &self.slots[i] {
                return v.clone();
            }
        }
        let v = s_get(&self.state, idx);
        if i >= self.slots.len() {
            self.slots.resize(i + 1, None);
        }
        self.slots[i] = Some(v.clone());
        v
    }

    fn set(&mut self, idx: u32, val: JsValue) {
        let i = idx as usize;
        if i >= self.slots.len() {
            self.slots.resize(i + 1, None);
        }
        self.slots[i] = Some(val);
        self.dirty.push(idx);
    }

    fn flush(&self) {
        for &slot in &self.dirty {
            if let Some(Some(v)) = self.slots.get(slot as usize) {
                s_set(&self.state, slot, v.clone());
            }
        }
    }

    fn flush_and_invalidate(&mut self) {
        self.flush();
        self.slots.clear();
        self.dirty.clear();
    }
}

// ---------------------------------------------------------------------------
// FN_REGISTRY – WeakMap<Function, {v, j, s: Uint32Array}>
//
// Populated by WasmPlatform::op_fn; checked by WasmPlatform::op_call to
// decide whether the callee can be dispatched directly in Rust (sync fast path).
// ---------------------------------------------------------------------------

thread_local! {
    static FN_REGISTRY: WeakMap = WeakMap::new();
}

fn registry_set(fn_val: &JsValue, variant: u32, j: u32, closure_slots: &[u32]) {
    FN_REGISTRY.with(|wm| {
        let entry = create_null_obj();
        let _ = Reflect::set(&entry, &JsValue::from_str("v"), &JsValue::from_f64(variant as f64));
        let _ = Reflect::set(&entry, &JsValue::from_str("j"), &JsValue::from_f64(j as f64));
        let arr = Uint32Array::new_with_length(closure_slots.len() as u32);
        for (i, &s) in closure_slots.iter().enumerate() {
            arr.set_index(i as u32, s);
        }
        let _ = Reflect::set(&entry, &JsValue::from_str("s"), &arr);
        wm.set(fn_val.unchecked_ref::<Object>(), &entry);
    });
}

fn registry_get(fn_val: &JsValue) -> Option<(u32, u32, Vec<u32>)> {
    FN_REGISTRY.with(|wm| {
        let entry = wm.get(fn_val.unchecked_ref::<Object>());
        if entry.is_undefined() {
            return None;
        }
        let v = Reflect::get(&entry, &JsValue::from_str("v")).ok()?.as_f64()? as u32;
        let j = Reflect::get(&entry, &JsValue::from_str("j")).ok()?.as_f64()? as u32;
        let s_val = Reflect::get(&entry, &JsValue::from_str("s")).ok()?;
        let s_arr: Uint32Array = s_val.unchecked_into();
        let slots: Vec<u32> = (0..s_arr.length()).map(|i| s_arr.get_index(i)).collect();
        Some((v, j, slots))
    })
}

// ---------------------------------------------------------------------------
// Child-state construction helpers
// ---------------------------------------------------------------------------

fn build_child_state(parent: &JsValue, closure_slots: &[u32]) -> JsValue {
    let child = create_null_obj();
    if closure_slots.is_empty() {
        return child;
    }
    let descs = create_null_obj();
    for &slot in closure_slots {
        let slot_key = JsValue::from_f64(slot as f64);
        let desc = create_null_obj();
        let pg = parent.clone();
        let ps = parent.clone();
        let get_fn = Closure::<dyn Fn() -> JsValue>::new(move || s_get(&pg, slot));
        let set_fn = Closure::<dyn Fn(JsValue)>::new(move |v: JsValue| s_set(&ps, slot, v));
        let _ = Reflect::set(&desc, &JsValue::from_str("get"), get_fn.as_ref());
        let _ = Reflect::set(&desc, &JsValue::from_str("set"), set_fn.as_ref());
        let _ = Reflect::set(&desc, &JsValue::from_str("enumerable"), &JsValue::TRUE);
        let _ = Reflect::set(&desc, &JsValue::from_str("configurable"), &JsValue::FALSE);
        get_fn.forget();
        set_fn.forget();
        let _ = Reflect::set(&descs, &slot_key, &desc);
    }
    js_define_properties(&child, &descs);
    child
}

fn build_child_state_fast(closure_slots: &[u32], cache: &mut StateCache) -> JsValue {
    let child = create_null_obj();
    for &slot in closure_slots {
        let val = cache.get(slot);
        let _ = Reflect::set(&child, &JsValue::from_f64(slot as f64), &val);
    }
    child
}

// ---------------------------------------------------------------------------
// THROUGH symbol helper
// ---------------------------------------------------------------------------

/// Returns the global `Symbol.for("jade.through")` used to tag pass-through
/// yields in doubleGen mode.  Matches the TypeScript `THROUGH` export from
/// `shims.ts` which also uses `Symbol.for`.
#[inline]
fn through_symbol() -> JsValue {
    js_sys::Symbol::for_("jade.through").into()
}

/// Wrap `value` in `{value, [THROUGH]: true}` to mark it as a pass-through
/// yield from a declared-generator executing under the doubleGen flag.
fn make_through_val(value: JsValue) -> JsValue {
    let obj = create_null_obj();
    let _ = Reflect::set(&obj, &JsValue::from_str("value"), &value);
    let _ = Reflect::set(&obj, &through_symbol(), &JsValue::TRUE);
    obj
}

// ---------------------------------------------------------------------------
// WasmPlatform – jade_vm_core::Platform impl for JsValue
// ---------------------------------------------------------------------------

struct WasmPlatform<'a> {
    cache: StateCache,
    global_this: &'a JsValue,
    nt: &'a JsValue,
    tenant: &'a JsValue,
    add_async: bool,
    add_gen: bool,
}

impl<'a> WasmPlatform<'a> {
    fn new(
        state: &JsValue,
        global_this: &'a JsValue,
        nt: &'a JsValue,
        tenant: &'a JsValue,
        add_async: bool,
        add_gen: bool,
    ) -> Self {
        Self {
            cache: StateCache::new(state.clone()),
            global_this,
            nt,
            tenant,
            add_async,
            add_gen,
        }
    }
}

impl jade_vm_core::State for WasmPlatform<'_> {
    type Value = JsValue;

    fn get(&mut self, idx: u32) -> JsValue { self.cache.get(idx) }
    fn set(&mut self, idx: u32, val: JsValue) { self.cache.set(idx, val) }
    fn flush(&mut self) { self.cache.flush() }
    fn flush_and_invalidate(&mut self) { self.cache.flush_and_invalidate() }
    fn state_ref(&self) -> JsValue { self.cache.state.clone() }
}

impl jade_vm_core::Ops for WasmPlatform<'_> {
    type Value = JsValue;
    type Error = JsValue;

    fn f64_val(&self, v: f64) -> JsValue { JsValue::from_f64(v) }
    fn str_val(&self, s: &str) -> JsValue { JsValue::from_str(s) }
    fn undefined(&self) -> JsValue { JsValue::UNDEFINED }
    fn err(msg: &'static str) -> JsValue { JsValue::from_str(msg) }

    fn define_properties(&self, target: &JsValue, props: JsValue) {
        tenant_call(self.tenant, "define", &[target.clone(), props]);
    }

    fn op_global(&self) -> JsValue {
        self.global_this.clone()
    }

    fn op_fn(
        &mut self,
        code: &[u8],
        variant: JsValue,
        closure_args: JsValue,
        spanner: JsValue,
        j: u32,
        parent_state: JsValue,
    ) -> Result<JsValue, JsValue> {
        let declared_variant = (variant.as_f64().unwrap_or(0.0) as u32) & 3;
        let effective_variant = declared_variant
            | (self.add_async as u32)
            | ((self.add_gen as u32) << 1);
        // doubleGen: addGen applied on top of a declared generator → YIELD tagging
        let child_double_gen = self.add_gen && (declared_variant & 2 != 0);

        let closure_slots: Vec<u32> = {
            let arr: Array = closure_args.unchecked_into();
            (0..arr.length())
                .map(|i| arr.get(i).as_f64().unwrap_or(0.0) as u32)
                .collect()
        };
        let closure_slots_reg = closure_slots.clone();

        let (spanner_fn, spans): (JsValue, Vec<JsValue>) =
            if spanner.is_null() || spanner.is_undefined() {
                (Function::new_with_args("a", "return a").into(), Vec::new())
            } else {
                let arr: Array = spanner.unchecked_into();
                let sp = arr.get(0);
                let extra: Vec<JsValue> = (1..arr.length()).map(|i| arr.get(i)).collect();
                (sp, extra)
            };

        let code_c: Vec<u8> = code.to_vec();
        let gt_c = self.global_this.clone();
        let tenant_c = self.tenant.clone();
        let add_async_c = self.add_async;
        let add_gen_c = self.add_gen;

        let inner = Closure::<dyn Fn(JsValue, Array) -> JsValue>::new(
            move |js_this: JsValue, js_args: Array| {
                let child = build_child_state(&parent_state, &closure_slots);
                dispatch_variant(
                    effective_variant, &code_c, &child, j,
                    &gt_c, &js_this, &tenant_c, &js_args,
                    add_async_c, add_gen_c, child_double_gen,
                )
            },
        );
        let inner_js = inner.into_js_value();
        let factory = Function::new_with_args("f", "return function(...a){return f(this,a)}");
        let wrapper = factory.call1(&JsValue::null(), &inner_js).map_err(|e| e)?;

        let spanned = if spans.is_empty() {
            wrapper
        } else if let Some(sp_fn) = spanner_fn.dyn_ref::<Function>() {
            let call_args = Array::new();
            call_args.push(&wrapper);
            for s in &spans {
                call_args.push(s);
            }
            Reflect::apply(sp_fn, &JsValue::null(), &call_args).unwrap_or(wrapper)
        } else {
            wrapper
        };

        // Register with the effective variant so op_call's fast path uses the right executor.
        registry_set(&spanned, effective_variant, j, &closure_slots_reg);
        Ok(spanned)
    }

    fn op_lit32(&self, val: u32) -> JsValue {
        JsValue::from_f64(val as f64)
    }

    fn op_arr(&self, items: Vec<JsValue>) -> JsValue {
        let arr = Array::new_with_length(items.len() as u32);
        for (i, v) in items.into_iter().enumerate() {
            arr.set(i as u32, v);
        }
        arr.into()
    }

    fn op_str(&self, cps: Vec<JsValue>) -> JsValue {
        let s: String = cps
            .into_iter()
            .filter_map(|v| char::from_u32(v.as_f64().unwrap_or(0.0) as u32))
            .collect();
        JsValue::from_str(&s)
    }

    fn op_litobj(&self, spread: Option<JsValue>, pairs: Vec<(JsValue, JsValue)>) -> JsValue {
        let obj = tenant_call(self.tenant, "make", &[JsValue::NULL]);
        if let Some(src) = spread {
            tenant_call(self.tenant, "assign", &[obj.clone(), src]);
        }
        for (k, v) in pairs {
            tenant_call(self.tenant, "set", &[obj.clone(), k, v]);
        }
        obj
    }

    fn op_new_target(&self) -> JsValue {
        self.nt.clone()
    }

    fn op_call(
        &mut self,
        code: &[u8],
        fn_val: JsValue,
        args: Vec<JsValue>,
    ) -> Result<JsValue, JsValue> {
        let call_args = Array::new_with_length(args.len() as u32);
        for (i, a) in args.into_iter().enumerate() {
            call_args.set(i as u32, a);
        }

        if let Some((variant_idx, j, closure_slots)) = registry_get(&fn_val) {
            if variant_idx == 0 {
                // Sync jade-to-jade: dispatch directly in Rust, no state flush.
                let child = build_child_state_fast(&closure_slots, &mut self.cache);
                let res = run_sync(
                    code, &child, j as usize,
                    self.global_this, &JsValue::UNDEFINED, self.tenant, &call_args,
                    self.add_async, self.add_gen,
                )
                .unwrap_or(JsValue::UNDEFINED);
                for &slot in &closure_slots {
                    self.cache.set(slot, s_get(&child, slot));
                }
                return Ok(res);
            }
        }

        self.cache.flush_and_invalidate();
        Ok(Reflect::apply(fn_val.unchecked_ref::<Function>(), &JsValue::UNDEFINED, &call_args)
            .unwrap_or(JsValue::UNDEFINED))
    }

    fn op_bool(&self, val: bool) -> JsValue { JsValue::from_bool(val) }

    fn op_eq(&self, a: JsValue, b: JsValue) -> JsValue { JsValue::from_bool(a == b) }
    fn op_ne(&self, a: JsValue, b: JsValue) -> JsValue { JsValue::from_bool(a != b) }
    fn op_lt(&self, a: JsValue, b: JsValue) -> JsValue {
        JsValue::from_bool(a.as_f64().zip(b.as_f64()).map_or(false, |(a, b)| a < b))
    }
    fn op_le(&self, a: JsValue, b: JsValue) -> JsValue {
        JsValue::from_bool(a.as_f64().zip(b.as_f64()).map_or(false, |(a, b)| a <= b))
    }
    fn op_gt(&self, a: JsValue, b: JsValue) -> JsValue {
        JsValue::from_bool(a.as_f64().zip(b.as_f64()).map_or(false, |(a, b)| a > b))
    }
    fn op_ge(&self, a: JsValue, b: JsValue) -> JsValue {
        JsValue::from_bool(a.as_f64().zip(b.as_f64()).map_or(false, |(a, b)| a >= b))
    }

    fn op_sel(&self, cond: JsValue, then: JsValue, else_: JsValue) -> JsValue {
        if cond.is_truthy() { then } else { else_ }
    }

    fn op_get(&self, obj: JsValue, key: JsValue) -> JsValue {
        tenant_call(self.tenant, "get", &[obj, key])
    }

    fn op_set(&self, obj: JsValue, key: JsValue, val: JsValue) -> JsValue {
        tenant_call(self.tenant, "set", &[obj, key, val.clone()]);
        val
    }

    // Run the loop body while the condition value is truthy; `init` is the
    // initial condition and each `body` call returns the next condition value.
    fn while_op<Ctx, F>(&mut self, ctx: &mut Ctx, init: JsValue, mut body: F) -> Result<JsValue, JsValue>
    where F: FnMut(&mut Self, &mut Ctx) -> Result<JsValue, JsValue> {
        let mut c = init;
        while c.is_truthy() {
            c = body(self, ctx)?;
        }
        Ok(c)
    }

    fn if_op<Ctx, FT, FE>(
        &mut self, ctx: &mut Ctx, cond: JsValue, then_body: FT, else_body: FE,
    ) -> Result<JsValue, JsValue>
    where
        FT: FnOnce(&mut Self, &mut Ctx) -> Result<JsValue, JsValue>,
        FE: FnOnce(&mut Self, &mut Ctx) -> Result<JsValue, JsValue>,
    {
        if cond.is_truthy() { then_body(self, ctx) } else { else_body(self, ctx) }
    }

    fn switch_op<Ctx, F, D>(
        &mut self, ctx: &mut Ctx, val: JsValue,
        cases: impl IntoIterator<Item = (u32, F)>, default_body: D,
    ) -> Result<JsValue, JsValue>
    where
        F: FnOnce(&mut Self, &mut Ctx) -> Result<JsValue, JsValue>,
        D: FnOnce(&mut Self, &mut Ctx) -> Result<JsValue, JsValue>,
    {
        let tag = val.as_f64().map(|v| v as u32);
        for (cv, branch) in cases {
            if tag == Some(cv) {
                return branch(self, ctx);
            }
        }
        default_body(self, ctx)
    }
}

// ---------------------------------------------------------------------------
// dispatch_variant – entry point for child functions created by FN opcode
// ---------------------------------------------------------------------------

fn dispatch_variant(
    variant_idx: u32,
    code: &[u8],
    state: &JsValue,
    ip: u32,
    global_this: &JsValue,
    nt: &JsValue,
    tenant: &JsValue,
    args: &Array,
    add_async: bool,
    add_gen: bool,
    double_gen: bool,
) -> JsValue {
    match variant_idx {
        0 => run_sync(code, state, ip as usize, global_this, nt, tenant, args, add_async, add_gen)
            .unwrap_or(JsValue::UNDEFINED),
        1 => {
            let code = code.to_vec();
            let state = state.clone();
            let gt = global_this.clone();
            let nt = nt.clone();
            let tenant = tenant.clone();
            let args = args.clone();
            future_to_promise(async move {
                run_async_internal(&code, &state, ip as usize, &gt, &nt, &tenant, &args, add_async, add_gen).await
            })
            .into()
        }
        2 => create_sync_gen(code, state, ip as usize, global_this, nt, tenant, add_gen, double_gen)
            .unwrap_or(JsValue::UNDEFINED),
        3 => create_async_gen(code, state, ip as usize, global_this, nt, tenant, add_gen, double_gen)
            .unwrap_or(JsValue::UNDEFINED),
        _ => JsValue::UNDEFINED,
    }
}

// ---------------------------------------------------------------------------
// Generator state machine
// ---------------------------------------------------------------------------

enum StepResult {
    Yielded(JsValue, u32),
    Returned(JsValue),
}

struct GenMachine {
    code: Vec<u8>,
    state: JsValue,
    ip: usize,
    pending_dest: Option<u32>,
    delegating: Option<(JsValue, u32)>,
    done: bool,
    global_this: JsValue,
    nt: JsValue,
    tenant: JsValue,
    add_async: bool,
    add_gen: bool,
    /// When true this function was a declared generator running under addGen;
    /// YIELD values are wrapped in the THROUGH tag to mark them as pass-throughs.
    double_gen: bool,
}

// ---------------------------------------------------------------------------
// run_sync
// ---------------------------------------------------------------------------

fn run_sync(
    code: &[u8],
    state: &JsValue,
    start_ip: usize,
    global_this: &JsValue,
    nt: &JsValue,
    tenant: &JsValue,
    _args: &Array,
    add_async: bool,
    add_gen: bool,
) -> Result<JsValue, JsValue> {
    let mut ip = start_ip;
    let mut platform = WasmPlatform::new(state, global_this, nt, tenant, add_async, add_gen);
    loop {
        let old_ip = ip;
        let (op, rest) = Operation::parse(&code[ip..])
            .ok_or_else(|| js_err("run_sync: unexpected end"))?;
        ip = code.len() - rest.len();

        match op {
            Operation::Ret(val_op) => {
                let val = jade_vm_core::resolve(val_op, &mut platform);
                platform.flush();
                return Ok(val);
            }
            Operation::Await { .. } => {
                platform.flush();
                let code_c = code.to_vec();
                let state_c = state.clone();
                let gt_c = global_this.clone();
                let nt_c = nt.clone();
                let tenant_c = tenant.clone();
                let promise = future_to_promise(async move {
                    run_async_internal(&code_c, &state_c, old_ip, &gt_c, &nt_c, &tenant_c, &Array::new(), add_async, add_gen).await
                });
                return Ok(promise.into());
            }
            Operation::Yield { .. } | Operation::Yieldstar { .. } => {
                platform.flush();
                return create_sync_gen(code, state, old_ip, global_this, nt, tenant, add_gen, false);
            }
            _ => jade_vm_core::exec_op(op, code, &mut platform, &mut ())?,
        }
    }
}

// ---------------------------------------------------------------------------
// run_async_internal
// ---------------------------------------------------------------------------

async fn run_async_internal(
    code: &[u8],
    state: &JsValue,
    start_ip: usize,
    global_this: &JsValue,
    nt: &JsValue,
    tenant: &JsValue,
    _args: &Array,
    add_async: bool,
    add_gen: bool,
) -> Result<JsValue, JsValue> {
    let mut ip = start_ip;
    let mut platform = WasmPlatform::new(state, global_this, nt, tenant, add_async, add_gen);
    loop {
        let old_ip = ip;
        let (op, rest) = Operation::parse(&code[ip..])
            .ok_or_else(|| js_err("run_async: unexpected end"))?;
        ip = code.len() - rest.len();

        match op {
            Operation::Ret(val_op) => {
                let val = jade_vm_core::resolve(val_op, &mut platform);
                platform.flush();
                return Ok(val);
            }
            Operation::Await { val: val_op, dest } => {
                let promise_val = jade_vm_core::resolve(val_op, &mut platform);
                platform.flush_and_invalidate();
                let resolved = JsFuture::from(Promise::resolve(&promise_val)).await?;
                platform.set(dest, resolved);
            }
            Operation::Yield { .. } | Operation::Yieldstar { .. } => {
                platform.flush();
                return Ok(create_async_gen(code, state, old_ip, global_this, nt, tenant, add_gen, false)?);
            }
            _ => jade_vm_core::exec_op(op, code, &mut platform, &mut ())?,
        }
    }
}

// ---------------------------------------------------------------------------
// gen_step_sync
// ---------------------------------------------------------------------------

fn gen_step_sync(m: &mut GenMachine, sent: JsValue) -> Result<StepResult, JsValue> {
    if let Some(dest) = m.pending_dest.take() {
        s_set(&m.state, dest, sent.clone());
    }

    if let Some((ref sub, dest)) = m.delegating.clone() {
        let next_fn = Reflect::get(sub, &JsValue::from_str("next")).unwrap_or(JsValue::UNDEFINED);
        let result = if next_fn.is_function() {
            Reflect::apply(next_fn.unchecked_ref::<Function>(), sub, &Array::of1(&sent))
                .unwrap_or(JsValue::UNDEFINED)
        } else {
            JsValue::UNDEFINED
        };
        let sub_done = Reflect::get(&result, &JsValue::from_str("done"))
            .unwrap_or(JsValue::FALSE)
            .is_truthy();
        let sub_value =
            Reflect::get(&result, &JsValue::from_str("value")).unwrap_or(JsValue::UNDEFINED);
        if sub_done {
            s_set(&m.state, dest, sub_value);
            m.delegating = None;
        } else {
            m.delegating = Some((sub.clone(), dest));
            return Ok(StepResult::Yielded(sub_value, u32::MAX));
        }
    }

    let code = m.code.clone();
    let global_this = m.global_this.clone();
    let nt = m.nt.clone();
    let tenant = m.tenant.clone();
    let add_async = m.add_async;
    let add_gen = m.add_gen;
    let mut platform = WasmPlatform::new(&m.state, &global_this, &nt, &tenant, add_async, add_gen);

    loop {
        let old_ip = m.ip;
        let (op, rest) = Operation::parse(&code[m.ip..])
            .ok_or_else(|| js_err("gen_step: unexpected end"))?;
        m.ip = code.len() - rest.len();

        match op {
            Operation::Ret(val_op) => {
                let val = jade_vm_core::resolve(val_op, &mut platform);
                m.done = true;
                platform.flush();
                return Ok(StepResult::Returned(val));
            }
            Operation::Await { .. } => {
                platform.flush();
                m.ip = old_ip;
                return Err(js_err("__jade_vm__upgrade_to_ag__"));
            }
            Operation::Yield { val: val_op, dest } => {
                let val = jade_vm_core::resolve(val_op, &mut platform);
                // doubleGen: this function was a declared generator running under
                // addGen, so its native yields are tagged as pass-throughs.
                let yield_val = if m.double_gen { make_through_val(val) } else { val };
                m.pending_dest = Some(dest);
                platform.flush();
                return Ok(StepResult::Yielded(yield_val, dest));
            }
            Operation::Yieldstar { val: val_op, dest } => {
                let sub = jade_vm_core::resolve(val_op, &mut platform);
                platform.flush();
                m.delegating = Some((sub, dest));
                return gen_step_sync(m, JsValue::UNDEFINED);
            }
            _ => jade_vm_core::exec_op(op, &code, &mut platform, &mut ())?,
        }
    }
}

// ---------------------------------------------------------------------------
// gen_step_async
// ---------------------------------------------------------------------------

async fn gen_step_async(
    code: Vec<u8>,
    state: JsValue,
    mut ip: usize,
    global_this: JsValue,
    nt: JsValue,
    tenant: JsValue,
    add_async: bool,
    add_gen: bool,
) -> Result<(StepResult, usize), JsValue> {
    let mut platform = WasmPlatform::new(&state, &global_this, &nt, &tenant, add_async, add_gen);
    loop {
        let old_ip = ip;
        let (op, rest) = Operation::parse(&code[ip..])
            .ok_or_else(|| js_err("gen_step_async: unexpected end"))?;
        ip = code.len() - rest.len();

        match op {
            Operation::Ret(val_op) => {
                let val = jade_vm_core::resolve(val_op, &mut platform);
                platform.flush();
                return Ok((StepResult::Returned(val), ip));
            }
            Operation::Await { val: val_op, dest } => {
                let promise_val = jade_vm_core::resolve(val_op, &mut platform);
                platform.flush_and_invalidate();
                let resolved = JsFuture::from(Promise::resolve(&promise_val)).await?;
                platform.set(dest, resolved);
            }
            Operation::Yield { val: val_op, dest } => {
                let val = jade_vm_core::resolve(val_op, &mut platform);
                platform.flush();
                // double_gen flag is passed in via GenMachine (not WasmPlatform here);
                // gen_step_async is called from the async gen closure which has access.
                // NOTE: double_gen tagging for async gen is applied at the call site below.
                return Ok((StepResult::Yielded(val, dest), ip));
            }
            Operation::Yieldstar { val: val_op, dest } => {
                let sub_iter = jade_vm_core::resolve(val_op, &mut platform);
                platform.flush_and_invalidate();
                let next_fn = Reflect::get(&sub_iter, &JsValue::from_str("next"))
                    .unwrap_or(JsValue::UNDEFINED);
                let raw_result = if next_fn.is_function() {
                    Reflect::apply(
                        next_fn.unchecked_ref::<Function>(),
                        &sub_iter,
                        &Array::of1(&JsValue::UNDEFINED),
                    )
                    .unwrap_or(JsValue::UNDEFINED)
                } else {
                    JsValue::UNDEFINED
                };
                let result = JsFuture::from(Promise::resolve(&raw_result)).await?;
                let sub_done = Reflect::get(&result, &JsValue::from_str("done"))
                    .unwrap_or(JsValue::FALSE)
                    .is_truthy();
                let sub_value = Reflect::get(&result, &JsValue::from_str("value"))
                    .unwrap_or(JsValue::UNDEFINED);
                if sub_done {
                    platform.set(dest, sub_value);
                } else {
                    platform.flush();
                    return Ok((StepResult::Yielded(sub_value, dest), ip));
                }
                let _ = old_ip;
            }
            _ => {
                jade_vm_core::exec_op(op, &code, &mut platform, &mut ())?;
                let _ = old_ip;
            }
        }
    }
}

// ---------------------------------------------------------------------------
// create_sync_gen
// ---------------------------------------------------------------------------

fn create_sync_gen(
    code: &[u8],
    state: &JsValue,
    start_ip: usize,
    global_this: &JsValue,
    nt: &JsValue,
    tenant: &JsValue,
    add_gen: bool,
    double_gen: bool,
) -> Result<JsValue, JsValue> {
    use alloc::rc::Rc;

    let machine = Rc::new(RefCell::new(GenMachine {
        code: code.to_vec(),
        state: state.clone(),
        ip: start_ip,
        pending_dest: None,
        delegating: None,
        done: false,
        global_this: global_this.clone(),
        nt: nt.clone(),
        tenant: tenant.clone(),
        add_async: false,
        add_gen,
        double_gen,
    }));

    let gen_obj = create_null_obj();

    let m_next = machine.clone();
    let next_fn = Closure::<dyn Fn(JsValue) -> JsValue>::new(move |sent: JsValue| {
        let mut m = m_next.borrow_mut();
        if m.done {
            return make_iter_result(JsValue::UNDEFINED, true);
        }
        match gen_step_sync(&mut m, sent) {
            Ok(StepResult::Yielded(val, _)) => make_iter_result(val, false),
            Ok(StepResult::Returned(val)) => {
                m.done = true;
                make_iter_result(val, true)
            }
            Err(upgrade) if upgrade == JsValue::from_str("__jade_vm__upgrade_to_ag__") => {
                let restart_ip = m.ip;
                let code_c = m.code.clone();
                let state_c = m.state.clone();
                let gt_c = m.global_this.clone();
                let nt_c = m.nt.clone();
                let tenant_c = m.tenant.clone();
                let add_gen_c = m.add_gen;
                let double_gen_c = m.double_gen;
                drop(m);
                let ag = create_async_gen(&code_c, &state_c, restart_ip, &gt_c, &nt_c, &tenant_c, add_gen_c, double_gen_c)
                    .unwrap_or(JsValue::UNDEFINED);
                make_iter_result(ag, false)
            }
            Err(e) => {
                m.done = true;
                make_iter_result(e, true)
            }
        }
    });

    let m_ret = machine.clone();
    let return_fn = Closure::<dyn Fn(JsValue) -> JsValue>::new(move |val: JsValue| {
        m_ret.borrow_mut().done = true;
        make_iter_result(val, true)
    });

    let m_throw = machine;
    let throw_fn =
        Closure::<dyn Fn(JsValue) -> Result<JsValue, JsValue>>::new(move |err: JsValue| {
            m_throw.borrow_mut().done = true;
            Err(err)
        });

    let _ = Reflect::set(&gen_obj, &JsValue::from_str("next"), next_fn.as_ref());
    let _ = Reflect::set(&gen_obj, &JsValue::from_str("return"), return_fn.as_ref());
    let _ = Reflect::set(&gen_obj, &JsValue::from_str("throw"), throw_fn.as_ref());

    next_fn.forget();
    return_fn.forget();
    throw_fn.forget();

    let sym_iter = js_sys::Symbol::iterator();
    let self_iter_factory = Function::new_with_args("g", "return function(){return g}")
        .call1(&JsValue::null(), &gen_obj)?;
    let _ = Reflect::set(&gen_obj, &sym_iter, &self_iter_factory);

    Ok(gen_obj)
}

// ---------------------------------------------------------------------------
// create_async_gen
// ---------------------------------------------------------------------------

fn create_async_gen(
    code: &[u8],
    state: &JsValue,
    start_ip: usize,
    global_this: &JsValue,
    nt: &JsValue,
    tenant: &JsValue,
    add_gen: bool,
    double_gen: bool,
) -> Result<JsValue, JsValue> {
    use alloc::rc::Rc;

    let machine = Rc::new(RefCell::new(GenMachine {
        code: code.to_vec(),
        state: state.clone(),
        ip: start_ip,
        pending_dest: None,
        delegating: None,
        done: false,
        global_this: global_this.clone(),
        nt: nt.clone(),
        tenant: tenant.clone(),
        add_async: true,
        add_gen,
        double_gen,
    }));

    let gen_obj = create_null_obj();

    let m_next = machine.clone();
    let next_fn = Closure::<dyn Fn(JsValue) -> Promise>::new(move |sent: JsValue| {
        let mc = m_next.clone();
        future_to_promise(async move {
            let (code, state, pending_dest, delegating, gt, nt, tenant, add_async, add_gen, double_gen) = {
                let mut m = mc.borrow_mut();
                if m.done {
                    return Ok(make_iter_result(JsValue::UNDEFINED, true));
                }
                (
                    m.code.clone(),
                    m.state.clone(),
                    m.pending_dest.take(),
                    m.delegating.take(),
                    m.global_this.clone(),
                    m.nt.clone(),
                    m.tenant.clone(),
                    m.add_async,
                    m.add_gen,
                    m.double_gen,
                )
            };

            if let Some(dest) = pending_dest {
                s_set(&state, dest, sent.clone());
            }

            if let Some((sub, dest)) = delegating {
                let next_js =
                    Reflect::get(&sub, &JsValue::from_str("next")).unwrap_or(JsValue::UNDEFINED);
                let raw_result = if next_js.is_function() {
                    Reflect::apply(next_js.unchecked_ref::<Function>(), &sub, &Array::of1(&sent))
                        .unwrap_or(JsValue::UNDEFINED)
                } else {
                    JsValue::UNDEFINED
                };
                let result = JsFuture::from(Promise::resolve(&raw_result)).await?;
                let sub_done = Reflect::get(&result, &JsValue::from_str("done"))
                    .unwrap_or(JsValue::FALSE)
                    .is_truthy();
                let sub_value = Reflect::get(&result, &JsValue::from_str("value"))
                    .unwrap_or(JsValue::UNDEFINED);
                if sub_done {
                    s_set(&state, dest, sub_value);
                    mc.borrow_mut().delegating = None;
                } else {
                    mc.borrow_mut().delegating = Some((sub, dest));
                    return Ok(make_iter_result(sub_value, false));
                }
            }

            let ip = mc.borrow().ip;
            let (step_result, new_ip) =
                gen_step_async(code, state, ip, gt, nt, tenant, add_async, add_gen).await?;

            {
                let mut m = mc.borrow_mut();
                m.ip = new_ip;
                match &step_result {
                    StepResult::Yielded(_, dest) if *dest != u32::MAX => {
                        m.pending_dest = Some(*dest)
                    }
                    StepResult::Returned(_) => m.done = true,
                    _ => {}
                }
            }

            Ok(match step_result {
                StepResult::Yielded(val, _) => {
                    let yield_val = if double_gen { make_through_val(val) } else { val };
                    make_iter_result(yield_val, false)
                }
                StepResult::Returned(val) => make_iter_result(val, true),
            })
        })
    });

    let m_ret = machine.clone();
    let return_fn = Closure::<dyn Fn(JsValue) -> Promise>::new(move |val: JsValue| {
        m_ret.borrow_mut().done = true;
        Promise::resolve(&make_iter_result(val, true))
    });

    let m_throw = machine;
    let throw_fn = Closure::<dyn Fn(JsValue) -> Promise>::new(move |err: JsValue| {
        m_throw.borrow_mut().done = true;
        Promise::reject(&err)
    });

    let _ = Reflect::set(&gen_obj, &JsValue::from_str("next"), next_fn.as_ref());
    let _ = Reflect::set(&gen_obj, &JsValue::from_str("return"), return_fn.as_ref());
    let _ = Reflect::set(&gen_obj, &JsValue::from_str("throw"), throw_fn.as_ref());

    next_fn.forget();
    return_fn.forget();
    throw_fn.forget();

    let sym_async_iter = js_sys::Symbol::async_iterator();
    let self_iter_factory = Function::new_with_args("g", "return function(){return g}")
        .call1(&JsValue::null(), &gen_obj)?;
    let _ = Reflect::set(&gen_obj, &sym_async_iter, &self_iter_factory);

    Ok(gen_obj)
}

// ---------------------------------------------------------------------------
// Public WASM exports
// ---------------------------------------------------------------------------

macro_rules! make_async_variant {
    ($name:ident) => {
        #[wasm_bindgen]
        pub async fn $name(
            code: Vec<u8>,
            state: JsValue,
            ip: u32,
            global_this: JsValue,
            nt: JsValue,
            tenant: JsValue,
            args: Array,
            add_async: bool,
            add_gen: bool,
        ) -> Result<JsValue, JsValue> {
            run_async_internal(&code, &state, ip as usize, &global_this, &nt, &tenant, &args, add_async, add_gen)
                .await
        }
    };
}

#[wasm_bindgen]
pub fn run_virtualized(
    code: Vec<u8>,
    state: JsValue,
    ip: u32,
    global_this: JsValue,
    nt: JsValue,
    tenant: JsValue,
    args: Array,
    add_async: bool,
    add_gen: bool,
) -> Result<JsValue, JsValue> {
    run_sync(&code, &state, ip as usize, &global_this, &nt, &tenant, &args, add_async, add_gen)
}

make_async_variant!(run_virtualized_a);

#[wasm_bindgen]
pub fn run_virtualized_g(
    code: Vec<u8>,
    state: JsValue,
    ip: u32,
    global_this: JsValue,
    nt: JsValue,
    tenant: JsValue,
    _args: Array,
    _add_async: bool,
    add_gen: bool,
    double_gen: bool,
) -> Result<JsValue, JsValue> {
    create_sync_gen(&code, &state, ip as usize, &global_this, &nt, &tenant, add_gen, double_gen)
}

#[wasm_bindgen]
pub fn run_virtualized_ag(
    code: Vec<u8>,
    state: JsValue,
    ip: u32,
    global_this: JsValue,
    nt: JsValue,
    tenant: JsValue,
    _args: Array,
    _add_async: bool,
    add_gen: bool,
    double_gen: bool,
) -> Result<JsValue, JsValue> {
    create_async_gen(&code, &state, ip as usize, &global_this, &nt, &tenant, add_gen, double_gen)
}
